name: Daily Cloudflare Deploy

on:
  schedule:
    # 한국 시간 기준 오전 9시, 오후 1시, 오후 6시, 밤 11시 (다양한 예약 포스팅 시간을 맞추기 위해 하루 4번 빌드)
    - cron: '0 0 * * *'
    - cron: '0 4 * * *'
    - cron: '0 9 * * *'
    - cron: '0 14 * * *'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Cloudflare Pages Deploy Hook
        run: |
          if [ -z "${{ secrets.CLOUDFLARE_DEPLOY_HOOK }}" ]; then
            echo "Error: CLOUDFLARE_DEPLOY_HOOK secret is not set."
            exit 1
          fi
          curl -X POST "${{ secrets.CLOUDFLARE_DEPLOY_HOOK }}"
